FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:gophers/archive

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux

ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/lib
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/go-1.10/bin:/go/bin

ENV GOPATH=/go

RUN mkdir -p /go/src

RUN apt-get install -y git curl golang-1.10-go

RUN apt-get update && apt-get install -y --no-install-recommends \
	  libopenmpi-dev \
	  build-essential \
	  cmake \
	  libgoogle-glog-dev \
	  libgtest-dev \
	  libiomp-dev \
	  libleveldb-dev \
	  liblmdb-dev \
	  libopencv-dev \
	  libsnappy-dev \
	  libprotobuf-dev \
	  protobuf-compiler \
	  cmake \
	  wget \
	  openmpi-bin \
	  openmpi-doc

RUN git clone --recursive https://github.com/pytorch/pytorch.git && cd pytorch
WORKDIR /pytorch
RUN git checkout v0.4.1
RUN git submodule update --init --recursive
RUN mkdir build
WORKDIR /pytorch/build
RUN apt install -y cmake
RUN apt install -y wget

RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
RUN apt-get update && apt-get install -y intel-mkl-64bit-2018.3-051
RUN echo "/opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/" > /etc/ld.so.conf.d/intel_mkl.conf
RUN ldconfig

RUN cmake .. -DBLAS="MKL" -DUSE_NATIVE_ARCH=ON -DBUILD_PYTHON=OFF -DMKL_INCLUDE_DIR=/usr/local/pkgs/caffe2-cuda9.0-cudnn7-0.8.dev-py36_2018.07.20/include/caffe2
RUN make -j `nproc` install
