FROM ubuntu:16.04

RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:gophers/archive

RUN apt update
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/go-1.10/bin:/go/bin
ENV RUN_TYPE=cpu
ENV GOPATH=/go

RUN mkdir -p /go/src

RUN apt-get update && apt-get install --fix-missing -y --no-install-recommends \
      linux-libc-dev

RUN apt-get update && apt-get install --fix-missing -y --no-install-recommends \
      libavcodec-dev  \
      libavcodec-ffmpeg56 \
      manpages-dev

RUN apt-get update && apt-get install --fix-missing -y --no-install-recommends \
      libopenmpi-dev \
      git \
      curl \
      golang-1.10-go

RUN apt-get update && apt-get install -y --no-install-recommends \
	  build-essential \
	  cmake \
	  git \
	  libgoogle-glog-dev \
	  libgtest-dev \
	  libiomp-dev \
	  libleveldb-dev \
	  liblmdb-dev \
	  libopencv-dev \
	  libopenmpi-dev \
	  libsnappy-dev \
	  libprotobuf-dev \
	  protobuf-compiler \
	  cmake \
	  wget

RUN apt-get update && apt-get install -y --no-install-recommends \
	  python-dev \
	  python-pip

RUN git clone --recursive https://github.com/pytorch/pytorch.git && cd pytorch
WORKDIR /pytorch
RUN git checkout v0.4.1
RUN git submodule update --init --recursive
RUN mkdir build
WORKDIR /pytorch/build

RUN pip install --upgrade pip
RUN pip install --user setuptools
RUN pip install --user \
      future \
      numpy \
      protobuf
RUN cmake .. -DBLAS="Eigen" -DUSE_NATIVE_ARCH=ON
RUN make -j 8 install
RUN ldconfig
