FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:gophers/archive

RUN apt update
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux
RUN apt install -y git curl golang-1.10-go

ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/lib
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/go-1.10/bin:/go/bin
ENV RUN_TYPE=gpu
ENV GOPATH=/go

RUN mkdir -p /go/src

RUN apt-get -qq update && apt-get -qq -y install curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=3 \
    && conda update conda
RUN conda install -c caffe2 caffe2-cuda9.0-cudnn7

RUN git clone --recursive https://github.com/pytorch/pytorch.git && cd pytorch
WORKDIR /pytorch
RUN git checkout v0.4.1
RUN git submodule update --init --recursive
RUN mkdir build
WORKDIR /pytorch/build
RUN apt install -y cmake
RUN cmake .. -DBLAS="MKL" -DUSE_NATIVE_ARCH=ON -DMKL_INCLUDE_DIR=/usr/local/pkgs/caffe2-cuda9.0-cudnn7-0.8.dev-py36_2018.07.20/include/caffe2
RUN rm /usr/local/lib/libssl.so.1.0.0
RUN rm /usr/local/lib/libcrypto.so.1.0.0
RUN make -j 8 install


#RUN apt-get update && apt-get install -y --no-install-recommends \
#	  build-essential \
#	  cmake \
#	  git \
#	  libgoogle-glog-dev \
#	  libgtest-dev \
#	  libiomp-dev \
#	  libleveldb-dev \
#	  liblmdb-dev \
#	  libopencv-dev \
#	  libopenmpi-dev \
#	  libsnappy-dev \
#	  libprotobuf-dev \
#	  openmpi-bin \
#	  openmpi-doc \
#	  protobuf-compiler \
#	  python-dev \
#	  python-pip
#
#RUN pip install --user \
#      future \
#      numpy \
#      protobuf
