FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:gophers/archive

RUN apt update
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux
RUN apt install -y git curl golang-1.10-go

ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/lib
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/go-1.10/bin:/go/bin
ENV RUN_TYPE=gpu
ENV GOPATH=/go

RUN mkdir -p /go/src

RUN apt-get -qq update && apt-get -qq -y install curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=3 \
    && conda update conda
RUN conda install -c caffe2 caffe2-cuda9.0-cudnn7
