FROM ubuntu:16.04
ENV TF_TYPE=cpu
ENV TF_DIR=/usr/local
ENV GOPATH=/go
ADD https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.8.0.tar.gz libtensorflow.tar.gz
RUN tar -C ${TF_DIR} -xzf libtensorflow.tar.gz
ENV LD_LIBRARY_PATH=/usr/local/lib
COPY graphpipe-tf /
RUN apt-get update && apt-get install -y ca-certificates
ENTRYPOINT ["/graphpipe-tf"]
