FROM golang:1.10
ENV TF_TYPE=cpu
ENV TF_DIR=/usr/local
ENV GOPATH=/go
RUN apt-get update && apt-get install -y ca-certificates libstdc++6
COPY graphpipe-tf /
COPY lib/libiomp5.so /usr/local/lib
COPY lib/libmklml_intel.so /usr/local/lib
COPY lib/libtensorflow.so /usr/local/lib
RUN ldconfig
ENTRYPOINT ["/graphpipe-tf"]
