FROM oraclelinux:7-slim
RUN yum -y update glibc
ENV TF_TYPE=cpu
ENV TF_DIR=/usr/local
ENV GOPATH=/go
ENV LD_LIBRARY_PATH=/usr/local/lib
COPY graphpipe-tf /
COPY lib/libiomp5.so /usr/local/lib
COPY lib/libmklml_intel.so /usr/local/lib
COPY lib/libtensorflow.so /usr/local/lib
ENTRYPOINT ["/graphpipe-tf"]
